# Phase 4: Template Management - Context

**Gathered:** 2026-01-31
**Status:** Ready for planning

<domain>
## Phase Boundary

Admins can create and manage report templates with metadata (name, code, category, version) and lifecycle (active/inactive). Templates are tenant-scoped and persistent in the database. Once created, templates appear in the list and can be used multiple times to generate reports.

**Not in scope:** Configuring checklist fields, photo settings, signature fields (Phase 5).

</domain>

<decisions>
## Implementation Decisions

### Template Listing
- Table rows layout (compact table with columns: name, code, category, status, version)
- Minimal filtering: status only (active/inactive toggle)
- Search box with instant filtering by name or code
- Default sort: alphabetical by name

### Template Creation (Excel Import)
- Templates created via Excel file upload, not manual field-by-field entry
- Admin enters: template name + category (from dropdown)
- Code auto-generated by system (based on category + sequence, e.g., COM-001)
- Excel expected columns: Section, Script Step (question text), Result Type (Drop Down or Text), Step Result Values (Yes/No/NA options)
- Validation: show ALL errors if Excel is invalid, don't partial import
- Preview required: show parsed sections and questions, admin confirms before saving
- After confirmation: template saved permanently to database

### Categories
- Predefined list (dropdown):
  - Commissioning
  - Inspection
  - Maintenance
  - Testing

### Scope & Visibility
- No global templates — each tenant has their own templates
- All users within tenant can see templates (read-only) to select when creating reports
- Only admins can create, edit, and manage templates
- Inactive templates hidden completely from regular users (admins see them with status filter)

### Claude's Discretion
- Excel parsing implementation details
- Preview UI layout
- Error message formatting
- Table column widths and styling

</decisions>

<specifics>
## Specific Ideas

- Excel import is the primary way to create templates — this matches the existing workflow where templates are designed in spreadsheets first
- Templates must persist in database and be reusable for multiple reports
- Code auto-generation follows pattern: category prefix + sequence number (e.g., COM-001, INS-002)

</specifics>

<deferred>
## Deferred Ideas

None — discussion stayed within phase scope.

Note: Checklist field configuration, photo settings, and signature fields are Phase 5.

</deferred>

---

*Phase: 04-template-management*
*Context gathered: 2026-01-31*
